name: fermipy
channels:
  - conda-forge
  - conda-forge/label/cf201901
  - fermi
dependencies:
  - fermitools
  - scipy
  - matplotlib
  - pyyaml
  - numpy
  - astropy
  - gammapy
  - healpy
  - ipython
  - pip
  - pip:
      - fermipy
